name: CI
on:
    push:
    pull_request:
        branches: [master]
jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Install modules
              run: npm i

            - name: Run build
              run: npm run build

            - name: Run ESLint
              run: npx eslint ./src/
